# Generated by Django 3.1.7 on 2021-03-02 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name="Category's name")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoplist.profile', verbose_name='Category author')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('link', models.TextField(default='Null', verbose_name='Link')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Month',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='item',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoplist.month', verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='item',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoplist.profile', verbose_name="Item's author"),
        ),
    ]
